# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [25]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
# Array del 0 al 9
array1 = np.arange(10)

# Mostrar array
print(array1)

# Mouestro el tipo de dato del array para asegurarme
print(type(array1))


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [169]:
# Array de ceros con 5 elementos
array_zeros = np.zeros(5)

# Asigné el valor 5 en la posición 2 del array
array_zeros[2] = 5

# Mostré el array
array_zeros

array([0., 0., 5., 0., 0.])

**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [168]:
# Matriz identidad de 3x3 con unos en la diagonal y ceros en el resto
array_zeros_ones = np.eye(3)

# Mostré la matriz
print(array_zeros_ones)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [172]:
arr = np.array([10, 20, 30, 40, 50])
print(f"Array original = {arr}")

#Sumo el array + 5
array_sumado = arr + 5
print(f"Array sumado = {array_sumado}")

print("--------------------------------")

#Genero el número random para hacer la multiplicación
num_random = randint(1,10)
print(f"Mi numero random es {num_random}")
array_multiplicado = arr * num_random
print(f"Array original multiplicado por un valor random = {array_multiplicado}")

Array original = [10 20 30 40 50]
Array sumado = [15 25 35 45 55]
--------------------------------
Mi numero random es 7
Array original multiplicado por un valor random = [ 70 140 210 280 350]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#Genero un array identidad 4x4 con 1 en la diagonal y lo demás son ceros
array_identidad = np.eye(4)

#Imprimo el array
print(f"La array identidad es: \n {array_identidad}")

La array identidad es: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [175]:
#Uso la función arange para que genere una matriz que llegue hasta el número 20 con paso 2, osea que solo muestre los números pares
array_num_pares = np.arange(0,22,2)
print(f"Array original = {array_num_pares}")

#Genero un número random para las operaciones
num_para_operar = randint(1,5)
print(f"Número para hacer operaciones: {num_para_operar}")

#Sumo
suma_pares = array_num_pares + num_para_operar 
#Resto
resta_pares = array_num_pares - num_para_operar
#Multiplico
multiplicacion_pares = array_num_pares * num_para_operar 
#Divido
division_pares = array_num_pares / num_para_operar

#Muestro los resultados con saltos de linea para su mejor comprensión
print(f"------------------------\nLa suma es: {suma_pares} \n------------------------ \nLa resta es: {resta_pares} \n----------------------- \nla multiplicación es: {multiplicacion_pares} \n------------------------ \nla división es: {division_pares}") 



Array original = [ 0  2  4  6  8 10 12 14 16 18 20]
Número para hacer operaciones: 2
------------------------
La suma es: [ 2  4  6  8 10 12 14 16 18 20 22] 
------------------------ 
La resta es: [-2  0  2  4  6  8 10 12 14 16 18] 
----------------------- 
la multiplicación es: [ 0  4  8 12 16 20 24 28 32 36 40] 
------------------------ 
la división es: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
